In [112]:
import spacy
from spacy.matcher import PhraseMatcher, Matcher
from spacy.language import Language
from spacy.tokens import Span
from spacy.util import filter_spans
import re
import pandas as pd
import joblib

In [113]:
nlp=spacy.load('en_core_web_md')
matcher_0 = PhraseMatcher(nlp.vocab, attr="LOWER")
matcher_1 = PhraseMatcher(nlp.vocab, attr="LOWER")
matcher_2 = Matcher(nlp.vocab)
matcher_3 = PhraseMatcher(nlp.vocab, attr="LOWER")
matcher_4 = PhraseMatcher(nlp.vocab, attr="LOWER")
matcher_5 = Matcher(nlp.vocab)

In [114]:
df=pd.read_csv('../saved_files/nlp_dataset/A_Z_medicines_dataset_of_India.csv')

df.head()

,id,name,price(₹),Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
0,1,Augmentin 625 Duo Tablet,223.42,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (500mg),Clavulanic Acid (125mg)
1,2,Azithral 500 Tablet,132.36,False,Alembic Pharmaceuticals Ltd,allopathy,strip of 5 tablets,Azithromycin (500mg),NaN
2,3,Ascoril LS Syrup,118.00,False,Glenmark Pharmaceuticals Ltd,allopathy,bottle of 100 ml Syrup,Ambroxol (30mg/5ml),Levosalbutamol (1mg/5ml)
3,4,Allegra 120mg Tablet,218.81,False,Sanofi India Ltd,allopathy,strip of 10 tablets,Fexofenadine (120mg),NaN
4,5,Avil 25 Tablet,10.96,False,Sanofi India Ltd,allopathy,strip of 15 tablets,Pheniramine (25mg),NaN

In [115]:
list1 = df['short_composition1'].dropna().unique().tolist()
list2 = df['short_composition2'].dropna().unique().tolist()


drug_list = list1+list2

print('drugs name:')
print(drug_list[:5])

print('total nunmber of drugs:',len(drug_list))

drugs name:
['Amoxycillin  (500mg) ', 'Azithromycin (500mg)', 'Ambroxol (30mg/5ml) ', 'Fexofenadine (120mg)', 'Pheniramine (25mg)']
total nunmber of drugs: 11503

In [116]:
pattern=r"\s*\(.*?\)"

for i in range(len(drug_list)):
    drug_list[i] = re.sub(pattern,"", drug_list[i].strip())

print(drug_list[:5])

['Amoxycillin', 'Azithromycin', 'Ambroxol', 'Fexofenadine', 'Pheniramine']

In [117]:
patterns = [nlp.make_doc(med) for med in drug_list]

matcher_0.add("DRUGS", patterns)

In [118]:
df_medicine_list= df['name'].dropna().unique().tolist()

raw_medicine_list= [ i.split() for i in df_medicine_list ]

print(len(raw_medicine_list))
raw_medicine_list[:5]

249398

[['Augmentin', '625', 'Duo', 'Tablet'],
 ['Azithral', '500', 'Tablet'],
 ['Ascoril', 'LS', 'Syrup'],
 ['Allegra', '120mg', 'Tablet'],
 ['Avil', '25', 'Tablet']]

In [119]:
          
# medicine_list= list(set(map(lambda x : ' '.join(x[:2]),raw_medicine_list)))


# print('medicine name:')
# print(medicine_list[10:30])

# print('total medicine:',len(medicine_list))

In [120]:
dosage_forms = [
'tablet','capsule','syrup','ointment','cream',
'gel','injection','drops','lotion','suspension'
]

In [121]:
processed_medicine=set()
for medicine in df_medicine_list:
    for dos_rm in dosage_forms:
        if(dos_rm in medicine.lower()):
            med=medicine.lower().replace(dos_rm,'')
            processed_medicine.add(med.strip())

processed_medicine = list(processed_medicine)
len(processed_medicine)

236780

In [122]:
processed_medicine

['proxil cv 200mg/125mg',
 'levotric 5mg',
 'cefamed t 500mg/62.5mg',
 'floxitis m oral',
 'lcef 500mg',
 'matce pg forte 1mg/1000mg/15mg  er',
 'dvert 8mg',
 'c bactum forte 1000mg/500mg',
 'oxetol xr 150',
 'zyhmg hp 150i.u',
 'licy 5mg',
 'sarvoxy cv 500mg/125mg',
 'ventirex-fm',
 'alzep 0.5mg',
 'miratas 50  er',
 'ragina m',
 'jestel 40',
 'donac 75mg',
 'rabefen d 200mg/20mg  sr',
 'linzobest 600mg',
 'lucoblock-lc',
 'morexim 200mg',
 'codine  4 mg/10 mg',
 'kapsulair lc 5mg/10mg',
 't-xime plus 200mg/200mg',
 'fermox 250mg  dt',
 'alspas-d',
 'more active 500mg',
 'pritorva 40mg',
 'cudox',
 'clarence ds duo oral',
 'genoformin g 2mg/500mg',
 'advent forte 457mg  tangy orange',
 'ivel 12mg',
 'tato 10mg',
 'itromaxx 100mg',
 'caremik 100mg',
 'corphen d',
 'periset',
 'remiflu 150',
 'urclar 250mg',
 'doxime 100mg  dt',
 'cefi o 200',
 'topnerve b',
 'omiclip d 10mg/20mg',
 'grid 1m  pr',
 'oxbaze 300',
 'theofresh 100mg',
 'sugest sg 200mg',
 'feburid 40',
 'sanocef 1000mg',
 'alivate 20mg',
 'brubact 200mg',
 'mebatic 250 mg/500 mg',
 'tigatuff',
 'griskin 250mg',
 'bisalto-m',
 'zlimetin 6mg',
 'nintenib 100',
 'orapin 5 md',
 'ovzole 20mg',
 'nelsid d 20 mg/100 mg',
 'procap 40mg',
 'stotrip 90mg/48mg/100mg',
 'dysel mr 250mg/50mg/325mg',
 'acin 250mg',
 'lofo 500mg',
 'enact',
 'metromax am 5 mg/50 mg',
 'mabtas n 100mg',
 'remudol 100 mg/500 mg',
 'voglistar-plus 0.2',
 'zoxil 500mg',
 'coldrest',
 'emprogest 400mg  sr',
 'qpmox cl 250mg/250mg',
 'dotasin 80mg/250mg',
 'etornext-er',
 'bactiazi 100mg',
 'biocizz 5mg',
 'kymotid-br',
 'culmi h 12.5mg/40mg',
 'neurocetam 800',
 'amoxyrite 500mg',
 'oven tz 200mg/600mg',
 'tamlof 50mg/500mg',
 'senaxia-b',
 'arixone 500mg',
 'lifix 200mg',
 'thiobest 4mg',
 'odicef o forte 100mg dry',
 'cefina 50mg',
 'ramocid d 30mg/20mg  sr',
 'asproge 200mg soft gelatin',
 'imcold jr',
 'enzocas forte 180mg/96mg/200mg',
 'ondimak 8mg',
 'rabcam l 75mg/20mg',
 'ketoron 200mg',
 'tenedose 20mg',
 'satasun',
 'pefax-mf',
 'perlutal-m 10mg',
 'acephar sp 100mg/325mg/15mg',
 'clavacen lb 500mg/125mg',
 'thyrobest 100mcg',
 'zuropraz-d 20  sr',
 'veox d 50mg/10mg',
 'aardex 4mg',
 'sri cz plus',
 'glimiprex mf forte 1  pr',
 'brivetam 100',
 'omr',
 'ursodox 150mg',
 'stator 20mg',
 'telmijub 20',
 'doxion 100mg',
 'lifcorcet-m',
 'tegod 6mg',
 'piprazole-dsr',
 'spacet 5mg',
 'acepal 100mg',
 'citzer cold new 5mg/500mg/5mg',
 'glimiauk m 2mg/500mg',
 'bisowin 5',
 'cfpod 50mg',
 'ani rox 150mg',
 'kapyl 40mg',
 'mokcan 500mg',
 'sanlol 40mg  sr',
 'bronkoril',
 'restoderm plus',
 'k-sure dandruff treatment',
 'felok',
 'xovoltib 40mg',
 'biotor 40mg',
 'rabicare-d',
 'maxtil 5mg',
 'meslataj dr 400mg',
 'oxirab 20mg',
 'coldhit',
 'cefam 500mg',
 'toripil 120mg',
 'alupectin s',
 'rethitron',
 'xceft lb 100mg',
 'liser 50mg',
 'chimoclav 500mg/100mg',
 'renitab 300mg',
 'glimu 2mg',
 'h-quine',
 'diarin-gm',
 'flo flox 200mg',
 'amoclox kid',
 'kezol',
 'dyspar 100mg',
 'giganite 2mg',
 'okavax std 1000pfu',
 'inflam p',
 'lxopi d 10mg/20mg',
 'pepraz-d  sr',
 'skizotus 300mg',
 'upmef spas 10mg/250mg',
 'piclin kid 5mg',
 'ronem 250 mg',
 'vercefta',
 'recotor gold 10mg',
 'zytee l',
 'amdipine 5mg',
 'encodin',
 'febutrax 40',
 'pime tz 1000mg/125mg',
 'rifagen 400mg',
 'replug 400mg',
 'ugr a softgel',
 'laxiden oral  sugar free',
 'kansulide 100mg',
 'monocard 20mg',
 'metcalf 500mg  sr',
 'triptop 10mg',
 'acecloven 100mg',
 'balo x 200mg',
 'clodus 5mg',
 'prenew m 750mcg/75mg',
 'rixicef plus dry',
 'ocidon',
 'oclam 500mg/125mg',
 'cubacef oz 200mg/500mg',
 'clitrin vaginal soft capsule',
 'doxosal 400',
 'winogem 1.4gm',
 'novamentin 875mg/125mg',
 'mebatox-c',
 'rime 200mg',
 'zoxton 2gm',
 'odeflox t 200mg/600mg',
 'flopep 10mg',
 'telryl a 40mg/5mg',
 'conclove 100mg',
 'gabarace-m',
 'rio s tablet',
 'aircef 50mg  dt',
 'nimy-p',
 'dimpy 1mg/ml',
 'hivas 80mg',
 'levoca 500mg',
 'stromix 75mg',
 'kolo 650',
 'levovil 5',
 'kacimark 250mg',
 'ursobact 300mg  sr',
 'satlon 4mg',
 'appysip',
 'rosucare 10mg',
 'td pill',
 'hhmus 0.03%',
 'lonazep 1mg  md',
 'lipidator 10mg',
 'zithrodol 500',
 'smflox 200mg',
 'zoff oz 200mg/500mg',
 'megaflox tz',
 'ovunal hp 10000iu',
 'channel 30  mr',
 'clavser 500mg/125mg',
 'desifer 100mg',
 'moxynix 250mg/125mg',
 'proton-np 200mg',
 'roxetomin 50mg',
 'fluzol 150mg',
 'itravew 200',
 'maxxpod 200mg  dt',
 'coutim 500mg',
 'tromed-mr',
 'storvas trio 75mg/20mg/75mg',
 'ogeston 200mg soft atin capsule',
 'setrase 10mg',
 'hyss',
 'roximclav 625',
 'cardiopril 5',
 'aphyren 200 sr',
 'youpod cv 200mg/125mg',
 'starcef 1000mg',
 'aclopod-cv',
 'auriase 5mg',
 'valclovir 500mg',
 'crezole 200',
 'pausera 500mg',
 'oxizec',
 'pregeb forte 75',
 'itradak',
 'xenadom 500',
 'cloffnic sp',
 'miotaz 4.5',
 'anze 500',
 'sitenali 50mg',
 'cholat 20mg',
 'veeradol 100mg',
 'adecort 6mg',
 'numistel-c',
 'sibazol 4mg',
 'tazowax 4000mg/500mg',
 'cefkan 1000mg',
 'emesol 4mg  md',
 'histaday 2.5mg/ml',
 'clobafit 5',
 'orinate 50mg',
 'lansoz d 10mg/30mg',
 'lupimon fx 10mg/120mg',
 'augpen lb 625',
 'mgdol 100mg',
 'etolol 120mg',
 'neuronox 100iu',
 'ursoford 300',
 'qflox tz 500mg/600mg',
 'tenlip-m forte  sr',
 'herpak 800mg',
 'cefsym tz 1000mg/125mg',
 'rinzicold  mango',
 'fayopod cv 200mg/125mg',
 'mucovert-cr',
 'zopcef 200mg',
 'sonaflam p 100mg/325mg',
 'rifik 400',
 'dicloril 50 mg/10 mg',
 'nacdon 25mg',
 'zufly-oz',
 'blumox p 125mg',
 'telmipil am 40mg/5mg',
 'acfac 100mg',
 'mycoclin 500mg  vt',
 'nexximox 500mg',
 'cefnosis 250mg',
 'glibamide m 5mg/500mg',
 'prezivas cv 10mg/75mg',
 'samic 100mg',
 'fluzin 20mg',
 'itraliv 100mg',
 'nimupan cold flu',
 'esmogud ls 75mg/40mg  sr',
 'ezicetri l 5mg',
 'recodex dx',
 'mofla 200mg',
 'amlodip 5mg',
 'anxiclo 0.25mg  md',
 'effelyte 600mg effervescent',
 'curesin 250mg',
 'itraboost 100mg',
 'molzin',
 'beeamoxy 500mg',
 'lenzit-m',
 'chymocad',
 'rient 20',
 'vomiline 4mg  md',
 'tacsite 0.03%',
 'rocknac mr 250mg/50mg/325mg',
 'zedrab 75mg/20mg  sr',
 'ban cold oral',
 'voglimark gm 2mg/500mg/0.2mg  sr',
 'jiyomic mf 500mg/250mg',
 'zidomax 300mg',
 'caldemure d3 soft gelatin',
 'pansec dsr',
 'grivicron forte 250mg',
 'gatia 200mg',
 'nemiva-s',
 'orflox oz 200mg/500mg',
 'tmatecad 50mg',
 'anutus d',
 'folgest 200mg',
 'fliptor 40mg',
 'ristclav 250mg/125mg',
 'oson o',
 'pantobull d  sr',
 'meconic pg 750mcg/75mg',
 'alfaren 200mg',
 'loparin 40',
 'ometor 20mg',
 'anitra 100',
 'zeox 50mg dry',
 'cassin 50mg dry',
 'cetro',
 'nyloflam-sp +',
 'ambzine 5mg/60mg',
 'amichlor 12.5 mg/5 mg',
 'daytime 5mg',
 'fergonad f 150iu',
 'dval 250mg',
 'gradnisone 16mg',
 'a-cet 5mg',
 'captar 40mg',
 'facid 20',
 'glimecon mv  sr',
 'angitab 10mg',
 'proplus 20mg',
 'rosulip 40',
 'asthamon-l',
 'niobe p 100mg/325mg',
 'kicwak',
 'telkonol  80mg',
 'e cin 250mg',
 'v mont-a',
 'symol 125mg/5ml/5mg/5ml',
 'sefonet 200mg',
 'coldnyl 500mg/30mg/4mg',
 'flax 200mg',
 'pregrin 5mg',
 'febrinil-cc cough & cold',
 'gabanerve nt 400mg/10mg',
 'evoce 5mg',
 'tamsukem plus',
 'vtuss ax',
 'edu ax',
 'loremfix 100mg',
 'robne dsr',
 'amiline 50mg',
 'meconem plus',
 'zidol 10mg',
 'enros 10mg',
 'duonim plus',
 'zivudin 300mg',
 'fylfot 500mcg',
 'loeva 200mg  sr',
 'moxyrise cv dry',
 'scotfix-o',
 'pilovate',
 'senac',
 'glycigon',
 'telcef 1000mg',
 'sandulose',
 'rabegut 20mg',
 'lydem 200mg',
 'tpant 40',
 'altex sugar-free',
 'cefdocil 50 dry',
 'ziokof l',
 'nicomax 20mg',
 'neurospas 20mg/500mg',
 'triz 500mg',
 'cufse',
 'rofex 500mg',
 'femol 650mg',
 'clobit 200mg  sr',
 'safetelmi ct 40mg/12.5mg',
 'isohib 90',
 'levozine 5mg',
 'omewan d 10mg/20mg  sr',
 'atocer-d 10mg/1000iu',
 'reva 100mg',
 'esxidar plus 0.5mg/10mg',
 'doxotero 10mg',
 'teldix 40',
 'ciz le d 5 mg/120 mg',
 'ecocid-dsr',
 'pantium 40mg',
 'mefdro spas',
 'thermal-s oral',
 'rebrex eye',
 'deonam 1000mg',
 'fexair 120mg',
 'betavert od 48  cr',
 'kubmef oral  mango',
 'wakactive 200mg',
 'dilozol o 50mg/5ml/125mg/5ml',
 'brenac-mr',
 'hbs 6',
 'nise spas ds 10 mg/50 mg',
 'benformin l s 1.25 mg/250 mg',
 'rzt 10mg  md',
 'scotlon 50',
 'ondiphar',
 'omzer-d',
 'sonirab 10 mg',
 'hybreed 40mg',
 'phensedyl dx',
 'tricofen 400mg',
 'daxiga 10',
 'amtrone 4mg  md',
 'cefobiz t 1000mg/125mg',
 'rapixim 200mg',
 'elicalm plus 10mg/2mg',
 'coller f oral',
 'tide e 20  combikit',
 'dulcen 20',
 'seclomed sp 100mg/325mg/15mg',
 'mox redimix 125 oral',
 'fluanxol depot 40mg',
 'gidilan 20mg',
 'kamfart',
 'betsone ds',
 'rhinokast f 10mg/120mg',
 'steflox 500mg',
 'safodex 50mg',
 'mlofen-mr',
 'mefnum spas 10 mg/250 mg',
 'szetalo plus',
 'betagesic k 10mg  dt',
 'n zone s 250mg/125mg',
 'aziser 250mg',
 'sneez bye',
 'hga 500mg',
 'jovastatin 5mg',
 'losaral 50mg',
 'vaxirab n 2.5iu',
 'intagesic sp',
 'astomet gp 2mg/500mg/15mg',
 'wonderm',
 'ivastar 5mg',
 'tirucoflox 200mg',
 'healcer 40mg',
 'cilapine 5',
 'lupase 25000',
 'elixi oz oral',
 'atikim 150mg',
 'abetanate',
 'cefpodax 50mg oral',
 'etromk 90mg',
 'hepakro ft 300mg',
 'domped 10mg',
 'silodova 8',
 'cognitriz m kid 2.5mg/4mg',
 'zefcon 150mg',
 'vofen sp 100 mg/500 mg/15 mg',
 'scyther 150mg',
 'lacef 250mg',
 'metamef-p',
 'fertova 50mg',
 'glimstin m 2mg/500mg',
 'olenix 7.5mg',
 'prazocip 5mg  xl',
 'nortis-tz',
 'rabolin dsr 30mg/20mg',
 'nurokript np 75mg/10mg/1500mcg',
 'esotrend 20',
 'nsd plus 100mg/500mg',
 'isopic 10mg soft atin capsule',
 'benzi 500',
 'notipram-plus 5',
 'riax-m xr 5mg/500mg',
 'rapixim-o',
 'toxo mox 500mg/125mg',
 'cough dm',
 'impraz-dsr',
 'fivasa',
 'iskopep 4000mg/500mg',
 'teneligold 20mg',
 'mefna dr 80mg/250mg',
 'ocuvir 3%',
 'teridax m',
 'liokast-m kid 2.5mg/4mg',
 'serranac-k 50mg/10mg',
 'flustan 200mg',
 'betayu 16mg',
 'adicart',
 'philcef 100 dt',
 'monogee 500mg',
 'oxyres 500mg',
 'xeratio 10mg',
 'omiget d 10mg/20mg',
 'progene 25mg',
 'etrosun 60mg/4mg  mr',
 'rabxo 20mg',
 'mefon 500',
 'kritnim p 100mg/325mg',
 'cephbid 250mg',
 'flumet 400mg',
 'yerab 20mg',
 'jike 500mg',
 'claripel plus 2%',
 'lacoxa 50mg',
 'clonaril 0.25mg',
 'raftaron 100mg/500mg',
 'terapal 500mg',
 'gerifen ar',
 'visial 1%',
 'retencal-plus',
 'nufix 200mg',
 'cobsa g 300mg/750mcg',
 'lipi 5mg',
 'tussin',
 'amlowood 5mg',
 'feburox 40mg',
 'avtop d 30mg/40mg  sr',
 'lithonik 400mg  sr',
 'itozole 200mg',
 'clavimox 125 mg/31.25 mg',
 'ocalm 0.5mg',
 'tripolin',
 'beclindone 200',
 'eviflox-oz',
 'flutix 20mg',
 'esogic-d  sr',
 'amitryptyline 10mg',
 'aximol-m',
 'selzic -od 300mg  er',
 'canfla sb 500mg/250mg',
 'omefit-d',
 'cefprov 100  dt',
 'pancort 30mg',
 'alenmox 500mg',
 'rrzole 20mg',
 'nkacin 500',
 'anacof-dm',
 'olmicure h 12.5mg/40mg',
 'inflanac 100mg',
 'ralgyz soft atin capsule',
 'augpen lb 375 mg',
 'ceftolon sb 1000mg/500mg',
 'falmet 80mg/480mg',
 'jydame 500mg',
 'cobix 200',
 'nash 100mg',
 'nikpar',
 'fertitone 300mg',
 'remet 100 mg/100 mg',
 'enflam sera',
 'vabrab 20',
 'venti',
 'sacdase d 50 mg/10 mg',
 'etonise plus 60mg/325mg',
 'acitrom 2',
 'amoxim 100mg  dt',
 'femipod cv 200mg/125mg',
 'dirifa 550',
 'provironum',
 'allbenda i 6mg/400mg',
 'ondalife oral',
 'rabedom 10 mg/20 mg',
 'fraxiparine 6150iu',
 'vilargy 5 mg/10 mg',
 'meconet 300mg/500mcg',
 'albenda 200mg',
 'azilide 250',
 'orthocort 24mg',
 'burlibact s 1000mg/500mg',
 'n met g 2mg/500mg',
 'colifast oral',
 'cvy mox dry',
 'vigrobol 25mg',
 'ambrozen-s',
 'aziblu 250',
 'opiof oz 200mg/500mg',
 'thysid-a',
 'cormin 500mcg',
 'ediflox oz',
 'mecolynn p',
 'oliza 2.5',
 'citirut-m',
 'betapro 60mg  sr',
 'defog 6mg',
 'ticalclav 3000mg/100mg',
 'muciday  sr',
 'elonac sp 100mg/325mg/15mg',
 'tanfix 100mg  dt',
 'healpil 50mg/10mg',
 'apar mr 100mg/500mg/250mg',
 'amoxreen cn 250mg/250mg',
 'gobac plus',
 'clores 10mg',
 'mascovent',
 'vedoxim 200  dt',
 'tizalud d 50 mg/2 mg',
 'amidine 5',
 'temflox 200mg',
 'solprazole-d 10mg/40mg',
 'broxil',
 'cefzidime tz 1.125gm',
 'moxletic-lb 625',
 'pansped d 10 mg/20 mg',
 'achetiva  sr',
 'laricef-o 200',
 'paclo np 100mg/325mg',
 'lubowel 8 soft atin capsule',
 'nineyes',
 'wapioderm 0.05%',
 'cefnus 100mg  dt',
 'leetic 100mg',
 'pregaba sr 75',
 'sayolexin 500mg',
 'clibtab d 2.5mg/5mg/10mg',
 'coriminic p',
 'graniden 1mg  md',
 'etoblis-p',
 'diagli 80mg',
 'cepotus 50mg  dt',
 'desrina 50  er',
 'glimed-mf 2/500 er',
 'montuvir 10mg',
 'nudiclo 75mg',
 'moxiruth 500mg',
 'ofencer 200mg',
 'cetaxol 5mg/60mg',
 'alo oz 200mg/500mg',
 'exclusive 200 mg/28.5 mg',
 'ceefcap 500mg',
 'r gesp 200mg soft gelatin',
 'rabolin-d',
 'flucaz 150mg',
 'rabicro-l  sr',
 'adpime 250mg',
 'clomit 50mg',
 'rabela-itr 20mg/150mg',
 'vomease 2mg oral',
 'rosucard 20',
 'caditor asp 10mg/75mg',
 'clamoxin 125 mg/31.5 mg',
 'alenfos 10mg',
 'roximeg 150mg',
 'esamlodose 2.5',
 'soval',
 'itowar 100mg',
 'kvmox 250',
 'metazide 80mg/500mg',
 'sureclav 625',
 'pregdox plus 10mg/25mg/5mg',
 'saveram 10',
 'itraxil 200mg',
 'dioglip-mp',
 'metnate 16mg',
 'lecet 10mg',
 'zefrox-cv 325',
 'amiject 500mg',
 'neurodin 1000mcg',
 'rabozec d 30 mg/20 mg',
 'atorica crc 40mg',
 'hymoxy cv lb 500mg/125mg',
 'sunglim m 1mg/500mg',
 'orimik 250mg',
 'dicbio-p',
 'macirol 10mg',
 'amlocos at 5mg/50mg',
 'megagam-n',
 'filtim 200mg  dt',
 'hilcit 5mg',
 'lorkinz-p',
 'ensorex 50mg',
 'kolmik 250mg',
 'letromet 2.5mg',
 'pilcef 2gm',
 'glexime-plus',
 'lafix 200mg/60million cells',
 'rxmef 100mg/5ml',
 'vildagipt-mf',
 'acepa mr',
 'enoxyprin 0.4',
 'acerein gm 50mg/750mg/250mg',
 'trilotuss-d',
 'cefro 250mg',
 'kopitof 200mg',
 'cosvom-md',
 'etilive 0.25mg',
 'vovilmet',
 'rabomac 20mg',
 'saxim 50mg  dt',
 'efpodox 200mg',
 'cijo-spas',
 'cefophil cv 200mg/125mg',
 'olagress md 5',
 'cefosul 1000mg/1000mg',
 'emegran 3 1mg',
 'oflosen 200mg',
 'micromox 250mg  dt',
 'proteclav dds 457 oral',
 'barozac 10mg',
 'defahit 6mg',
 's gary 400mg',
 'ofrex eye/ear',
 'c freedo 0.25mg',
 'cfr 250mg',
 'gram pn 1000mg',
 'betalar 0.5mg',
 'roxtil 250',
 'paarmol',
 'c.p. mol',
 'gabaco 300mg',
 'sol u pred 500mg',
 'rufenac',
 'concid i.v.',
 'zekocid d sr 30mg/20mg',
 'kitlus',
 'este 250mg',
 'volcet m 5mg/10mg',
 'solocef 1000mg',
 'etolam 0.5mg  md',
 'rabzone 20mg',
 'berycef 250',
 'zeroflame sp 100mg/325mg/15mg',
 'regan 10mg',
 'albafen',
 'rivaflo 15',
 'tegliwyn m 500mg/20mg',
 'abifabin 300mg/500mcg',
 'androrise',
 'samtide 50mg',
 'wikipod 100mg',
 'maxformin 1000mg  sr',
 'aldust l 5mg',
 'fluxazole dsr',
 'femexel 500 mg/125 mg',
 'ramicon 1.25mg',
 'ngsart ch 40mg/12.5mg',
 'yogatel 40',
 'ojiderm it',
 'morpred 8',
 'azpik 250mg',
 'cefanz az 200mg/200mg',
 'vernet 6',
 'vobligo 0.3mg',
 'serallect ap 100 mg/325 mg/15 mg',
 'wyserin 500mg',
 'glimed mf 3mg/1000mg  sr',
 'ozerol 20',
 'amione 100mg',
 'idehist 8mg',
 'fivdoxi cv 200mg/125mg',
 'estxone sb 250mg/125mg',
 'candiwell 100mg',
 'emdox 100mg',
 'fenobax sp 100mg/325mg/15mg',
 'sofia 100mg',
 'omizol d',
 'megaplat 100mg',
 'mordox cv dry',
 'xolocold',
 'zomox cl 250 mg/125 mg',
 'amlorate 2.5mg',
 'ceflan 250mg',
 'mecever',
 'uliject 100000iu',
 'augmed 1000 mg/200 mg',
 'teldix-a',
 'rexim 200 lb  dt',
 'vildaspec m 500mg/50mg',
 'nova-d 50  dr',
 'helinase 5mg',
 'desveren 100  er',
 'kesropan d 30mg/40mg  sr',
 'pantop-d',
 'histroy oral',
 'alfio fx 10mg/120mg',
 'nebidol 2.5mg',
 'ridol 20mg',
 'uniclox 500mg/500mg',
 'mintclav 500mg/125mg',
 'hextradol p   325 mg/37.5 mg',
 'mytrip h 12.5mg/5mg',
 'touchflam 100mg/325mg/15mg',
 'nimp plus 100mg/325mg',
 'amikos 250mg',
 'folraise-dha soft capsule',
 'oaxime 50mg dry',
 'oflomac dx eye/ear',
 'amicest 200mg',
 'cefilab 200',
 'lorhist 10mg',
 'rozatoss 20',
 'vancofast 1000mg',
 'kancin 500mg',
 'rayclav 1000mg/200mg',
 'xpera',
 'teldiac 40',
 'udiglac 300mg',
 'optel ch 40mg/12.5mg',
 'biopregab 75mg',
 'tepid 650mg',
 'supratum cv 500mg/125mg',
 'descet 5mg',
 'nimprest p 100mg/325mg',
 'cetiday cold new 5mg/500mg/5mg',
 'oxprin 60mg/0.6ml',
 'varnglim 1mg/500mg  sr',
 'zeben 200mg',
 'biover 6mg',
 'examin-mf',
 'levonez 500mg',
 'tadafil 20mg',
 'avclin',
 'telmicam cn 10mg/40mg',
 'urozap 400mg',
 'synac r 100mg/325mg/10mg',
 'miconiv p 750mcg/75mg',
 'lavixime 50mg dry',
 'zocol 50mg',
 'montegress 10mg',
 'relexi d 10mg/20mg  sr',
 'rescalm-az 0.25mg/20mg',
 'merolon 1000mg',
 'moxinem-cv dry',
 'roxirite 150mg',
 'tramagesic 100mg',
 'gzor mp 2mg/500mg/15mg',
 'keflex bd 750 mg',
 'montac l',
 'r cold plus oral',
 'olmetime 20',
 'epry 50mg',
 'citopam 40 mg',
 'zeodic-ds',
 'lewel 5mg',
 'roxin 50mg',
 'volitis',
 'etodix 120mg',
 'ulsore',
 'emtriaxone 1000mg',
 'pritorva 20mg',
 'camadol 100mg',
 'stayhappi domperidone+rabeprazole 30mg/40mg',
 'acedence 100mg/325mg',
 'moxibond oral',
 'novofran oral',
 'gucef s 500mg/250mg',
 'pas p 100mg/500mg',
 'udspas-d',
 'ictacetam 500mg',
 'chymonac forte',
 'fexolla 120',
 'vizcort 6mg',
 'mo zine 5mg/10mg',
 'stabose m 500mg/0.3mg',
 'emsilac 100mg',
 'emeran 2mg/5ml',
 'grodec 25mg',
 'dapatos 10mg',
 'efta t 250mg/31.25mg',
 'fevorit cv  dt',
 'zolydep 0.25mg',
 'tonac p oral',
 'stalvert 20mg/40mg',
 'cefanz lb 200mg',
 'equitrol 250mg',
 'janisha',
 'oxeltra 600mg',
 'brifcort oral',
 'nimosho total',
 'pentarim-dsr',
 'amick 500mg',
 'lidox 200  dt',
 'nosicure oral',
 'lococerin 50mg',
 'lyricet m',
 'mergin 0.125mg',
 'prompt dsr 30mg/40mg',
 'divalcure xr 250',
 'zoxlet m',
 'azibig 250mg',
 'cezof sb 1000mg/500mg',
 'erox cv 625',
 'folimost',
 'stupan d 10mg/40mg',
 'priglip m 500mg/20mg',
 'vocium soft gelatin',
 'terifin 25mg',
 'sulphonorm m 2mg/500mg  sr',
 'itrostred 200',
 'eutropin 4iu',
 'fadvic 80 mg',
 'solodoxim-cv',
 'sylster tx 250mg/250mg',
 'flexpod 200mg',
 'ramifid 10mg',
 'azpil 500mg',
 'elcisan',
 'ethvom 4mg  md',
 'rifonis 550',
 'whitish',
 'must lc',
 'beepraz l 75mg/20mg',
 'etizit 0.25  md',
 'cefpozest 200mg',
 'o m t',
 'rabeone d 30mg/20mg  sr',
 'vildalip-met 50/850',
 'angiotensin 5mg',
 'bonepex-d',
 'glucodrive g forte 1mg/1000mg  sr',
 'capcefo t 1000mg/125mg',
 'melcort',
 'roza 5',
 'sincare 500 mg/60 mg/2.5 mg',
 'dinflam 75mg',
 'telmicia h 40mg/12.5mg',
 'cititop 500mg',
 'goldmet g 2  pr',
 'fluri 10mg',
 'monobact 250 mg/125 mg',
 'nortrip 50mg',
 'fenmic spas 10mg/250mg',
 'deriphyllin s 231mg/69mg/4mg  pr',
 'pantika 40mg',
 'ompramil 20mg',
 'prime 500  sr',
 'suseiz 1mg',
 'cevy 50mg dry',
 'clariwar 250mg',
 'hadlev-m',
 'rabiquaa 30mg/20mg  sr',
 'polostan-sr',
 'invanz 1gm',
 'ofior 50mg/5ml',
 'cincar 200mg',
 'fixer 50mg dry',
 'itracobin 200',
 'purich 800mg',
 'b cozy',
 'throxid 150mg',
 'ventocortil 5',
 'amglow-plus',
 'etizip 0.5mg',
 'omesan dm 10mg/20mg',
 'nitrazepam 10mg',
 'xanid 200mg/500mg',
 'ebertiv',
 'evclav lb 625',
 'sugaflo 10mg',
 'seotac 20mg',
 'defrab-d',
 'tofe',
 'azimet 250mg',
 'rasodan d',
 'unimac 200mg/20mg  sr',
 'azimon 500mg',
 'bioryl-dp',
 'glador m 2 forte  pr',
 'p pan d 30mg/40mg  sr',
 'alentos 0.5mg',
 'aprazol 0.5mg',
 'myone depot 150 mg',
 'olmiswift 20mg',
 'oser dm 10mg/40mg',
 'tpther 50mg',
 'itroryn 200mg',
 'woncocid o',
 'metel a 40mg/5mg',
 'loprin-ds',
 'krishbactum-plus',
 'rabwave d 30mg/20mg',
 'doloxy cv oral',
 'carina-cv 325',
 'alnahist 8mg',
 'nervelex',
 ...]

In [123]:
patterns = [nlp.make_doc(med) for med in processed_medicine]

matcher_1.add("MEDICINE", patterns)

In [124]:
pattern = [
    {"LIKE_NUM": True},
    {"LOWER": {"IN": ["mg", "ml","g","mcg"]}}
]

matcher_2.add("DOSAGE", [pattern])

In [125]:
doc = nlp("Doctor gave me paracetamol 500mg and Dolo 650 for fever")

print("PhraseMatcher Results:")
for match_id, start, end in matcher_0(doc):
    print("drug:", doc[start:end].text)

print("\nPhraseMatcher Results:")
for match_id, start, end in matcher_1(doc):
    print("Medicine:", doc[start:end].text)

print("\nMatcher Results:")
for match_id, start, end in matcher_2(doc):
    print("Dosage:", doc[start:end].text)

PhraseMatcher Results:
drug: paracetamol

PhraseMatcher Results:
Medicine: paracetamol
Medicine: Dolo
Medicine: Dolo 650

Matcher Results:
Dosage: 500mg

In [126]:
disease_dataset = pd.read_csv('../saved_files/nlp_dataset/Disease and symptoms dataset.csv')

disease_name = disease_dataset['diseases'].dropna().unique().tolist()

In [127]:
disease_list = list(map(lambda x: x.lower(),disease_name)) 
print('disease name:')
print(disease_list[:5])
print('total disease:',len(disease_list))

disease name:
['panic disorder', 'vocal cord polyp', 'turner syndrome', 'cryptorchidism', 'poisoning due to ethylene glycol']
total disease: 773

In [128]:
patterns = [nlp.make_doc(med) for med in disease_list]

matcher_3.add("DISEASES", patterns)

In [129]:
add_common_disease = pd.read_csv('../saved_files/nlp_dataset/symptom_dataset.csv')  

common_disease = add_common_disease['Symptom_Name'].tolist()

In [130]:
patterns = [nlp.make_doc(med) for med in common_disease]

matcher_4.add("SYMPTOM", patterns)

In [131]:
print('symptoms name:')

print(common_disease[:5])

print('total symptoms:',len(common_disease))

symptoms name:
['Fever', 'High fever', 'Mild fever', 'Low-grade fever', 'Continuous fever']
total symptoms: 229

In [132]:
pattern_1 = [
    {"LIKE_NUM": True},
    {"LOWER": {"IN": ["day", "days", "week", "weeks", "month", "months"]}}
]

pattern_2 = [
    {"LOWER": {"IN": ["yesterday", "today", "tomorrow"]}}
]

pattern_3 = [
    {"LOWER": "day"},
    {"LOWER": "before"},
    {"LOWER": "yesterday"}
]

pattern_4 = [
    {"LOWER": "last"},
    {"LOWER": {'IN': ['day','month','week','year','morning','afternoon','evening','night']}},

]

matcher_5.add("DURATION", [pattern_1])
matcher_5.add("RELATIVE_DATE", [pattern_2, pattern_3,pattern_4])

In [133]:
matchers = [
    (matcher_0, "DRUG"),
    (matcher_1, "MEDICINE"),
    (matcher_2, "DOSAGE"),
    (matcher_4, "SYMPTOM"),
    (matcher_3, "DISEASE"),
    (matcher_5, "TIME_EXPRESSION"),
]

In [134]:
@Language.component("medical_matcher")
def medicine_words(doc):

    new_ents = list(doc.ents)

    for matcher, label in matchers:
        for _, start, end in matcher(doc):

            span = Span(doc, start, end, label=label)

            new_ents = [
                e for e in new_ents
                if not (e.start < end and e.end > start)
            ]

            new_ents.append(span)

    doc.ents = filter_spans(new_ents)
    return doc

In [135]:
nlp.add_pipe("medical_matcher", after="ner")

print(nlp.pipe_names)

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner', 'medical_matcher']

In [136]:
import dateparser

In [137]:
# doc = nlp("Doctor gave me paracetamol 500mg and Dolo 650 for fever FOR TOMORROW")
# doc=nlp('my sister are feeling pain in legs for 3 days')
# doc=nlp('my sister have cold sore')
# doc=nlp('i am feeling severe pain in legs for 3 days')

def content_details(doc):
    trigger_verbs = ["have",'give', 'take', "suffer", "experience", "diagnose", "feel",'be']

    severity_map = {
    "severe": ["severe", "extreme", "intense", "unbearable", "very bad","very severe","critical","acute","serious"],
    "moderate": ["moderate", "average", "normal pain","chronic"],
    "mild": ["mild", "slight", "little", "light"]
    }
    
    self_terms = {"i", "me","mine"}

    family_terms = {
        "mother","father","mom","dad","brother","sister",
        "uncle","aunt","grandmother","grandfather",
        "son","daughter","wife","husband","child","baby","aunt"
    }

    friend_terms = {
        "friend","buddy","colleague","roommate",
        "classmate","neighbor"
    }


    def identify_subject(text):
        doc = nlp(text)

        for token in doc:
            word = token.text.lower()

            if word in family_terms:
                return word
            elif word in friend_terms:
                return "friends"
            elif word in self_terms:
                return "I"
    
    def get_severity(text):
        text = text.lower()

        for level, words in severity_map.items():
            for word in words:
                if word in text:
                    return level

        return None

    detail_extract={'patient': None,
    'severity':None,
    'condition':None,
    'disease':None,
    'medicine':None,
    'duration':None,
    'timestamp':None
    }

    detail_extract['severity']=get_severity(doc.text)
    
    detail_extract['patient']= identify_subject(doc)

    for ent in doc.ents:
        if ent.label_ == "MEDICINE":
            detail_extract['medicine'] = ent.text 
        if ent.label_ == "DISEASE":
            detail_extract['disease'] = ent.text
        if ent.label_ == "SYMPTOM":
            detail_extract['condition'] = ent.text
        if ent.label_ == "TIME_EXPRESSION" or ent.label_ == 'DATE':
            detail_extract['duration'] = ent.text
                        

                    
    if(detail_extract['duration']):
        parsed_date = dateparser.parse(detail_extract['duration'])
        try:
            formatted_date = parsed_date.strftime("%d/%m/%Y")
            detail_extract['timestamp']=formatted_date
        except:
            detail_extract['timestamp'] = None

    return detail_extract

In [138]:
disease_dataset[disease_dataset['diseases'].str.contains('ulcer', case=False)]

,diseases,anxiety and nervousness,depression,shortness of breath,depressive or psychotic symptoms,sharp chest pain,dizziness,insomnia,abnormal involuntary movements,chest tightness,...,stuttering or stammering,problems with orgasm,nose deformity,lump over jaw,sore in nose,hip weakness,back swelling,ankle stiffness or tightness,ankle weakness,neck weakness
127604,decubitus ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
127605,decubitus ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
127606,decubitus ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
127607,decubitus ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
127608,decubitus ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242346,gastroduodenal ulcer,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242347,gastroduodenal ulcer,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242348,gastroduodenal ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242349,gastroduodenal ulcer,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
242350,gastroduodenal ulcer,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [139]:
df[df['name'].str.contains('augmentin', case=False)]

,id,name,price(₹),Is_discontinued,manufacturer_name,type,pack_size_label,short_composition1,short_composition2
0,1,Augmentin 625 Duo Tablet,223.42,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (500mg),Clavulanic Acid (125mg)
13,14,Augmentin Duo Oral Suspension,67.20,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,bottle of 30 ml Oral Suspension,Amoxycillin (200mg),Clavulanic Acid (28.5mg)
45,46,Augmentin DDS Suspension,173.00,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,bottle of 30 ml Oral Suspension,Amoxycillin (400mg/5ml),Clavulanic Acid (57mg/5ml)
91,92,Augmentin 1000 Duo Tablet,601.45,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (875mg),Clavulanic Acid (125mg)
102,103,Augmentin 375 Tablet,229.00,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (250mg),Clavulanic Acid (125mg)
122,123,Augmentin 1.2gm Injection,156.14,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,vial of 1 Powder for Injection,Amoxycillin (1000mg),Clavulanic Acid (200mg)
243,244,Augmentin ES Oral Suspension,203.28,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,bottle of 50 ml Oral Suspension,Amoxycillin (600mg/5ml),Clavulanic Acid (42.9mg/5ml)
925,926,AUGMENTIN 375 DUO TABLET,229.00,True,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,strip of 10 tablets,Amoxycillin (250mg),Clavulanic Acid (125mg)
1180,1181,Augmentin 500mg/100mg Injection,101.02,True,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,vial of 10 ml Injection,Amoxycillin (500mg),Clavulanic Acid (100mg)
1243,1244,Augmentin 250mg/50mg Injection,68.00,False,Glaxo SmithKline Pharmaceuticals Ltd,allopathy,vial of 10 ml Injection,Amoxycillin (250mg),Clavulanic Acid (50mg)

In [140]:
add_common_disease[add_common_disease['Symptom_Name'].str.contains('ulcer', case=False)]

     Symptom_ID   Symptom_Name
135         136    Mouth ulcer
227         228          ulcer
228         229  stomach ulcer

In [141]:
demo=[
    "I have had a severe headache for the past 3 days.",

"My stomach has been hurting since last night.",

"I feel dizzy whenever I stand up.",

"I have chest pain and shortness of breath.",

"My child has a fever of 102°F since yesterday.",

"I am experiencing nausea and vomiting after eating.",

"There is swelling and redness around my ankle.",

"I have dry cough and mild fever.",

"My throat is sore and I can't swallow properly.",

"I have frequent urination and burning sensation.",

'i am suffering from fever',

]

In [ ]:
demo=[
'I have fever',
'I have cough',
'I took Augmentin 625 duo',
'I feel mild pain',
'I have diabetes',
'I took azithral',
'I have severe headache',
'I feel dizziness',
'i apply halovate cream',
'what is dolo 650',
'it is any serious issue if i feel severe headache'
]

In [143]:
for word in demo:
    doc=nlp(word)
    print(doc)
    print(content_details(doc),end='\n\n')

I have fever
{'patient': 'I', 'severity': None, 'condition': 'fever', 'disease': None, 'medicine': None, 'duration': None, 'timestamp': None}

I have cough
{'patient': 'I', 'severity': None, 'condition': 'cough', 'disease': None, 'medicine': None, 'duration': None, 'timestamp': None}

I took Augmentin 625 duo
{'patient': 'I', 'severity': None, 'condition': None, 'disease': None, 'medicine': 'Augmentin 625 duo', 'duration': None, 'timestamp': None}

I feel mild pain
{'patient': 'I', 'severity': 'mild', 'condition': 'pain', 'disease': None, 'medicine': None, 'duration': None, 'timestamp': None}

I have diabetes
{'patient': 'I', 'severity': None, 'condition': None, 'disease': 'diabetes', 'medicine': None, 'duration': None, 'timestamp': None}

I took azithral
{'patient': 'I', 'severity': None, 'condition': None, 'disease': None, 'medicine': 'azithral', 'duration': None, 'timestamp': None}

I have severe headache
{'patient': 'I', 'severity': 'severe', 'condition': 'headache', 'disease': None, 'medicine': None, 'duration': None, 'timestamp': None}

I feel dizziness
{'patient': 'I', 'severity': None, 'condition': 'dizziness', 'disease': None, 'medicine': None, 'duration': None, 'timestamp': None}

i apply halovate cream
{'patient': 'I', 'severity': None, 'condition': None, 'disease': None, 'medicine': 'halovate', 'duration': None, 'timestamp': None}

what is dolo 650
{'patient': None, 'severity': None, 'condition': None, 'disease': None, 'medicine': 'dolo 650', 'duration': None, 'timestamp': None}

In [144]:
with open('demo_nlp_text.txt','+r') as file:
    result= file.read()


pattern=r'[^A-Za-z0-9 \n \t]'

filter_result=re.sub(pattern,'',result)
print(filter_result)

SRI DHANVANTHRY
MEDICALS
1102 SOUTH MAIN STREET MAIN ROAD TAPANASAM
DLNOTUT214820 TUT214820GSTIN33AAPM3480A12D
Ph2243572 7639554605
CASH Bill No 61678
Date 011125
Time 185504
Dr PKRISHNAMURTHY MD
Name RAVI
Address

QTY MRP PARTICULARS RACK MFR BATCH EXP AMOUNT
10 29966 RENERVE PLUS CAP 15 MM GRAN GREL2509 0627 19977
TOTSGST 476
TOTCGST 476
TOTCOST 476
Total 19976

ID RAJAGOPAL
Goods once sold cannot be taken back
E  OE
Phar Sign
VRAMKUMAR
WISH YOU SPEEDY RECOVERY

Sub Total 19976
Discount 0
Total 19900

In [145]:
doc=nlp(filter_result)

for ent in doc.ents:
    print(ent.text," ",ent.label_ )
    # # print(ent.text," ", ent.label_)
    # if(ent.label_=='DOSAGE' or ent.label_=='MEDICINE'):
    #     print(ent.text," ",ent.label_)

MEDICALS   ORG
1102   CARDINAL
7639554605   DATE
PKRISHNAMURTHY   ORG
RAVI
Address   ORG
EXP   CARDINAL
10 29966   CARDINAL
RENERVE PLUS   MEDICINE
CAP   MEDICINE
15 MM GRAN GREL2509   QUANTITY
19977   DATE
476   CARDINAL
476   CARDINAL
476   CARDINAL
19976   DATE
OE   DATE
Phar Sign
VRAMKUMAR   ORG
19976   DATE
0   CARDINAL

In [146]:
doc=nlp("Take paracetamol 500mg twice daily")

for i, ent in enumerate(doc.ents):
    if ent.label_ == "MEDICINE" or ent.label_ == "DRUG":
        if i + 1 < len(doc.ents):
            next_ent = doc.ents[i + 1]
            if next_ent.label_ == "DOSAGE":
                print(ent.text, "->", next_ent.text)

paracetamol -> 500mg

In [147]:
nlp.to_disk('../saved_files/medical_nlp_model')